### ISSUE TITLE
Not able to login.

### ISSUE THREAD

**Issue by kashyap2108** [hatchet-dev/hatchet-go-quickstart#3]
After setting up docker compose and caddyfile in local , when i enter http://localhost:9099/ in browser it redirects to **http://localhost:9099/onboarding/verify-email** and there's no option to go anywhere . when i click on top right side icon and click logout , then i'm getting Internal err.

**Comment by altkashyap** [comment]
caddy was not able to redirect . so used nginx here and was able to open the page .
but now facing another issue.
Register or login api response is fine , but `v1/users/current` api is returning 403 forbidden
![Screenshot 2024-05-12 at 1 04 49 PM](https://github.com/hatchet-dev/hatchet-go-quickstart/assets/104635967/1be9f2e8-c619-499c-b194-2e7b726bf65
![Screenshot 2024-05-12 at 1 05 01 PM](https://github.com/hatchet-dev/hatchet-go-quickstart/assets/104635967/a6699c65-0bc6-40ba-9e23-fbd6b9a87aa2)
1)

**Comment by kashyap2108** [comment]
working fine . updated the env host for localhost
